config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'events#index'

  devise_for :users

  resources :users
  resources :events
  resources :attendances


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  belongs_to :user
  belongs_to :event

  after_create :attending_event_send

  def attending_event_send
    UserMailer.attending_event_email(self.event.administrator, self.user).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord

  has_many :attendances
  has_many :users, through: :attendances
  belongs_to :administrator, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord

  has_many :attendances
  has_many :events, through: :attendances
  has_many :event_admin, foreign_key: "administrator_id", class_name: "Event"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send

  def welcome_send
   UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def create
    if current_user == nil
      redirect_to root_path
    end
    @event = Event.find(params[:format])

    Attendance.create(:user => current_user, :event => @event, :stripe_customer_id => params[:stripeToken])
    flash[:success] = "Congratulations! You just joined the event."
    redirect_to event_path(params[:format])

    # Amount in cents
    @amount = @event.price * 100

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
    })

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path

  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user, only: [:new]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @event_end = @event.start_date + (@event.duration * 60)

    @admin = is_admin?
    @attendee = is_attendee?

  end

  def create

    @user = current_user

    @event = Event.new(:administrator => @user, :start_date => params[:start_date], :duration => params[:duration], :title => params[:title], :description => params[:description], :price => params[:price], :location => params[:location])
      if @event.save
        redirect_to root_path
      else
        render events_path
      end
  end


  private

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_user_session_path
    end
  end

  def is_admin?
    if current_user == @event.administrator
      true
    end
  end

  def is_attendee?
    if @event.users.include?(current_user)
      true
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user, only: [:show]
  before_action :is_logged_user

  def show
    @user = current_user
    @user_events = User.find(params[:id]).event_admin
  end

end

private

def authenticate_user
  unless current_user
    flash[:danger] = "Please log in."
    redirect_to root_path
  end
end

  def is_logged_user
    unless current_user.id == params[:id].to_i
      flash[:danger] = "You can only visit your profile."
      redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(type)
  case type
    when 'notice' then "alert-info"
    when 'success' then "alert-success"
    when 'error' then "alert-danger"
    when 'alert' then "alert-warning"
  end
end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/create.html.erb
<h1> Create </h1>
<p> <%= @params %></p>

app/views/attendances/index.html.erb
<h1> Index </h1>

app/views/attendances/new.html.erb
<h1> New </h1>

app/views/events/_card_events.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Kit UI</title>
<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">
</head>
<body>
    <div class="container">
      <div class="row d-flex justify-content-center ">

        <% @events.each do |n| %>
          <div class="col-sm-4">
            <div class="d-flex justify-content-center">

              <div class="card" style="width: 25rem; ">
                <%= image_tag "#{n.price.digits.last}.jpg", class: 'card-img-top' %>
                <div class="card-body">
                  <h5 class="card-title"><%= n.title[0,30] %>
                    <% unless n.title.size < 30 %>
                    ...
                    <% end %></h5>
                  <p class="card-text"><%= n.start_date.to_formatted_s(:short) %> • <%= n.location[0,15] %>...</p>

                    <div>
                      <div>
                        <span class="badge badge-primary"> <%= n.price %> € </span>
                        <% unless n.users.count == 0 %>
                        <span class="badge badge-success"> <%= n.users.count %>
                          <% if n.users.count == 1 %>
                          guest
                          <% else %>
                          guests </span>
                          <% end %>
                        <% end %>
                      </div>
                    </div><br>

                  <div class="container">
                    <a <%= link_to "View", event_path(n)%> </a>
                  </div>

                </div>
              </div>

        </div><br><br>
        </div>
        <% end %>

        <!-- <div class="card border-secondary mb-3" style="max-width: 20rem;">
          <div class="card-header"></div>
            <div class="card-body">
              <img style="height: 200px; width: 100%; display: block;"src="img/alexander-popov-hTv8aaPziOQ-unsplash.jpg" alt="Card image">
              <h4 class="card-title pt-2">Title of the event</h4>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
            <div class="modal-footer justify-content-start">
            <button type="button" class="btn btn-success">Join the event</button>
          </div>
      </div>
      <div class="card border-secondary mb-3" style="max-width: 20rem;">
        <div class="card-header"></div>
          <div class="card-body">
            <img style="height: 200px; width: 100%; display: block;"src="img/fidel-fernando-249DzAuJTqQ-unsplash.jpg" alt="Card image">
              <h4 class="card-title pt-2">Title of the event</h4>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
            <div class="modal-footer justify-content-start">
              <button type="button" class="btn btn-success">Join the event</button>
          </div>
      </div>
      <div class="card border-secondary mb-3" style="max-width: 20rem;">
        <div class="card-header"></div>
          <div class="card-body">
            <img style="height: 200px; width: 100%; display: block;"src="img/kelsey-chance-tAH2cA_BL5g-unsplash.jpg" alt="Card image">
            <h4 class="card-title pt-2">Title of the event</h4>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
            <div class="modal-footer justify-content-start">
              <button type="button" class="btn btn-success">Join the event</button>
            </div>
      </div>
      <div class="card border-secondary mb-3" style="max-width: 20rem;">
        <div class="card-header"></div>
          <div class="card-body">
            <img style="height: 200px; width: 100%; display: block;"src="img/samantha-gades-fIHozNWfcvs-unsplash.jpg" alt="Card image">
            <h4 class="card-title pt-2">Title of the event</h4>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
          <div class="modal-footer justify-content-start">
            <button type="button" class="btn btn-success">Join the event</button>
          </div>
      </div>
      <div class="card border-secondary mb-3" style="max-width: 20rem;">
        <div class="card-header"></div>
          <div class="card-body">
            <img style="height: 200px; width: 100%; display: block;"src="img/vishnu-r-nair-m1WZS5ye404-unsplash.jpg" alt="Card image">
            <h4 class="card-title pt-2">Title of the event</h4>
              <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          </div>
          <div class="modal-footer justify-content-start">
            <button type="button" class="btn btn-success">Join the event</button>
          </div>
      </div>
  <div class="card border-secondary mb-3" style="max-width: 20rem;">
    <div class="card-header"></div>
      <div class="card-body">
        <img style="height: 200px; width: 100%; display: block;"src="img/baim-hanif-pYWuOMhtc6k-unsplash.jpg" alt="Card image">
        <h4 class="card-title pt-2">Title of the event</h4>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      </div>
      <div class="modal-footer justify-content-start">
        <button type="button" class="btn btn-success">Join the event</button>
      </div> -->
  </div>
</div>
</body>
</html>

app/views/events/_card_participants.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Kit UI</title>
<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">
</head>
<body>
  <div class="text-center pt-1">
    <h1 class="display-3 mt-4 mb-3 text-primary">Participants</h1>
       <p>List of the ones who joined</p>
  </div>
    <div class="container d-flex justify-content-center">
      <div class="my-3 p-3 bg-white rounded box-shadow">
            <h2 class="border-bottom border-gray pb-2 mb-0 text-muted">Recent updates</h2>
            <div class="media text-muted pt-3">
              <img data-src="holder.js/32x32?theme=thumb&amp;bg=007bff&amp;fg=007bff&amp;size=1" alt="32x32" class="mr-2 rounded" style="width: 32px; height: 32px;" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%2232%22%20height%3D%2232%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_16caefd1d68%20text%20%7B%20fill%3A%23007bff%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A2pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_16caefd1d68%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20fill%3D%22%23007bff%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2212.296875%22%20y%3D%2216.9%22%3E32x32%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true">
              <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark"><%= @event.users.count %></strong>
                Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
              </p>
            </div>
            <% if @event.users.count == 1  %>
            <% else %>
          <% end  %>
          <% @event.users.each do |u| %>

          <li> <%= u.email %>
            <% end %> </li><br>



          <% unless @admin || @attendee || current_user == nil %>
            <div class="row justify-content-center">

              <%= form_tag attendances_path(@event) do %>
                <article>
                  <% if flash[:error].present? %>
                    <div id="error_explanation">
                      <p><%= flash[:error] %></p>
                    </div>
                  <% end %>
                <label class="amount">
                  <span> Amount: <%= @event.price %>.00€  </span>
                </label>
                </article>

                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                        data-description="Pay and join event."
                        data-amount="<%= @event.price * 100 %>"
                        data-locale="auto"></script>
              <% end %>

            </div><br><br>
          <% end %>
</body>
</html>

app/views/events/_ressource_event.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Kit UI</title>
<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">
<body>
  <div class="text-center pt-1">
    <h1 class="display-3 mt-4 mb-3 text-primary">Event</h1>
       <p>Know everything about the event !</p>
  </div>
  <div class = "container d-flex justify-content-start">
    <div class="row">
      <div class="col-8">
          <%= image_tag "#{@event.price.digits.last}-h.jpg", class: 'card-img-top' %>
      </div>
      <div class="col-4 card border-primary">
            <div class="card-body">
              <h2 class="card-title"><%= @event.title %></h2>
              <p class="card-text"><%= @event.administrator.first_name %> <%= @event.administrator.last_name %></p>
              <h5 class="card-title pt-2"><%= @event.start_date.to_formatted_s(:long) %> <br>
              <%= @event.location %></h5>

            </div>
      </div>
    </div>
  </div>
  <div class = "container">
    <div class="row">
      <div class="col-8">
          <div class="card-body">
            <h4 class="card-title">Description</h4>
              <p class="card-text"><%= @event.description %></p>
          </div>
      </div>
      <div class="col-4 card-body">
        <% if current_user == nil %>
      <button type="button" class="btn btn-success" style="width: 100%;"><%= link_to "Login to join", new_user_session_path %></button>
        <div class="social-icons d-flex justify-content-between mt-5">
          <% end %>
                <a href="#">
                  <i class="fab fa-linkedin-in fa-2x"></i>
                </a>
                <a href="#">
                  <i class="fab fa-twitter fa-2x"></i>
                </a>
                <a href="#">
                  <i class="fab fa-facebook fa-2x"></i>
                </a>
                <a href="#">
                  <i class="fab fa-instagram fa-2x"></i>
                </a>
          </div>
      </div>
    </div>
  </div>

</body>
</html>

app/views/events/index.html.erb
<%= render "shared/banner" %>


<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Eventbrite</h1>
  <p class="lead">All the events in Eventbrite. Stay tuned!</p>
</div>

<div class="row justify-content-center">
  <a class="btn btn-success btn-lg" <%= link_to "Create New Event", new_event_path %></a>
</div> <br><br>


<%= render "card_events" %>

app/views/events/new.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">New Event</h1>
  <p class="lead">Create your own events.</p>
</div>

<br>

<div class="container">
  <%= form_tag events_path do %>
  <div class="form-group">
    <%= date_field_tag('start_date', '', class:'form-control', required:'true', required:'true', autofocus: 'true')%>
  </div>
  <div class="form-group">
    <%= text_field_tag('duration', '', class:'form-control', required:'true', placeholder:"Duration (in minutes)", required:'true')%>
  </div>
  <div class="form-group">
    <%= text_field_tag('title', '', class:'form-control', required:'true', placeholder:"Title", required:'true')%>
  </div>
  <div class="form-group">
    <%= text_area_tag('description', '', class:'form-control', required:'true', placeholder:"Description", required:'true')%>
  </div>
  <div class="form-group">
    <%= text_field_tag('price', '', class:'form-control', required:'true', placeholder:"Price", required:'true')%>
  </div>
  <div class="form-group">
    <%= text_field_tag('location', '', class:'form-control', required:'true', placeholder:"Location", required:'true')%>
  </div>
  <%= submit_tag "Submit", class: 'btn btn-default btn btn-success' %>
</div>
<% end %>

app/views/events/show.html.erb
<%= render "ressource_event" %>
<%= render "card_participants" %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Kit UI</title>
<meta charset="utf-8">
<link rel="stylesheet" href="style.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">
<body>
  <footer class="container py-5">
      <div class="row">
        <div class="col-12 col-md">
          <i class="fas fa-calendar-week fa-3x"></i><br><br>
          <small class="d-block mb-3 text-muted">Eventbrite© 2018-2018</small>
        </div>
        <div class="col-6 col-md text-primary">
          <h5>Planifier vos événements</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted"" href="#">Créer un évenement</a></li>
            <li><a class="text-muted" href="#">S'inscrire à un événement</a></li>
          </ul>
        </div>
        <div class="col-6 col-md text-primary">
          <h5>Restons connectés</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Contacter la team</a></li>
            <li><a class="text-muted" href="#">Facebook</a></li>
            <li><a class="text-muted" href="#">Twitter</a></li>
            <li><a class="text-muted" href="#">Instagram</a></li>
          </ul>
        </div>
      </div>
  </footer>
</body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Kit UI</title>
<link rel="stylesheet" href="style.css">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="#">Menu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
     <ul class="navbar-nav mr-auto">
       <li class="nav-item active">
          <a class="nav-link" <%= link_to "Home", events_path %> </a>
      </li>
      <li class="nav-item dropdown form-inline my-2 my-lg-0">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <% if current_user == nil %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a <%= link_to "Login", new_user_session_path, :class => "dropdown-item" %> </a>
          <a <%= link_to "Create Account", new_user_registration_path, :class => "dropdown-item" %> </a>
        </div>
        <% else %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a <%= link_to "Profil", user_path(current_user.id), :class => "dropdown-item" %> </a>
          <a <%= link_to "Sign out", destroy_user_session_path, :class => "dropdown-item", method: :delete %> </a>
        </div>
        <% end %>
        </li>
          <li class="nav-item active">
          <a class="nav-link" href="#">About Eventbrite</a>
        </li>
    </ul>
   </div>
 </nav>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrite4</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="style.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <%= render 'layouts/flash'%>
    <%= yield %>
    <%= render 'layouts/footer'%>

    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Eventbrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
      </li>
    </ul>

      <li class="nav-item dropdown form-inline my-2 my-lg-0">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <% if current_user == nil %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a <%= link_to "Login", new_user_session_path, :class => "dropdown-item" %> </a>
          <a <%= link_to "Create Account", new_user_registration_path, :class => "dropdown-item" %> </a>
        </div>
        <% else %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a <%= link_to "Profil", user_path(current_user.id), :class => "dropdown-item" %> </a>
          <a <%= link_to "Sign out", destroy_user_session_path, :class => "dropdown-item", method: :delete %> </a>
        </div>
        <% end %>
      </li>
  </div>
</nav>

<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" role='alert'><%= value %></div>
  <% end %>

</body>

<%= yield %> -->

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_banner_small.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Kit UI</title>
<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">
<body>
  <header class="masterhead">
      <div class="container h-100">
        <div class="row h-100 align-items-center justify-content-center text-center">
            <h1 class="display-2 text-secondary font-weight-bold">About u<3</h1>
          </div>
          </div>
    </header>
</body><
</html>

app/views/users/_profile.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Kit UI</title>
<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.10.1/css/all.css" integrity="sha384-wxqG4glGB3nlqX0bi23nmgwCSjWIW13BdLUEYC4VIMehfbcro/ATkyDsF/AbIOVe" crossorigin="anonymous">
<body>
  <section class="resume-section p-3 p-lg-5 d-flex align-items-center text-center" id="about">
        <div class="w-100">
          <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="img/profile.jpg" alt="">
          <h1 class="mb-0"><%= @user.first_name %>
            <span class="text-primary"><%= @user.last_name %></span>
          </h1>
          <div class="subheading mb-5">
            <a href="mailto:name@email.com"><%= @user.email %></a>
          </div>
          <a <%= link_to "Edit", edit_user_registration_path %> </a>
          <p class="lead mb-5">I<%= @user.description %></p>
          <div class="social-icons">
            <a href="#">
              <i class="fab fa-linkedin-in"></i>
            </a>
            <a href="#">
              <i class="fab fa-github"></i>
            </a>
            <a href="#">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
              <i class="fab fa-facebook-f"></i>
            </a>
          </div>
        </div>
      </section>
</body>
</html>

app/views/users/show.html.erb
<%= render "banner_small"%>
<%= render "profile"%>
<br>

<div class="container">
  <div class="row">
    <% @user_events.each do |n| %>
      <div class="col-6">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-body">
                <h5 class="mb-1"><%= n.title %></h5>
                <p class="card-text"><%= n.description %></p>
              <div class="d-flex w-100 justify-content-between">
                <a <%= link_to "View", event_path(n.id)%> </a>
                <div>
                </div>
              </div>
              </div>
            </div>
          </div>
        </div><br>
      </div>
    <% end %>
  </div>
</div>